version: '2'
services:
  redis:
    image: "redis:alpine"
  user-service:
    image: "webdevtoolsandtech/user-service"
    environment:
      - REDIS_ADDRESS=redis:6379
  currency-calculator:
    build: .
    volumes:
     - ./server:/server
    command:
        python3 -u /server/server.py --host 0.0.0.0 --port 80
  frontend-service:
    image: "webdevtoolsandtech/currency-frontend"
  currency-backend:
    image: "webdevtoolsandtech/currency-backend"
    environment:
      - REDIS_ADDRESS=redis:6379
      - SESSION_SECRET="lalala"
      - USER_SERVICE_ADDRESS=user-service:80
      - FRONTEND_ADDRESS=frontend-service:80
      - CALCULATOR_ADDRESS=currency-calculator:80
    ports:
     - "3000:80"
